name: "My joke Pipeline"
run-name: ${{github.actor}} We are tesing github Action
on: 
  push:
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install dad-jokes package
        run: npm install --global @mikemcbride/dad-jokes

      - name: Test dad-jokes CLI
        run: dad-jokes