name: "My joke Pipeline"
run-name: ${{github.actor}} We are tesing github Action
on: 
  push:

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
            node-version: "18"
      - name: Install dad-jokes package
        run: npm install --global @mikemcbride/dad-jokes

      - name: Test dad-jokes CLI
        run: dad-jokes
      - uses: actions/checkout@v4
      - run: dad-jokes >> blague.txt
      - run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b joke-reports
          git add blague.txt
          git commit -m "ma blague"
          git push origin joke-reports --force
    